platform :ios, '9.3'

#use_frameworks!
inhibit_all_warnings!

target 'app' do
	pod 'Crashlytics'
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'OneSignal'
    pod 'Realm/Headers'
    pod 'Realm', '~> 1.1.0'
	pod 'SinchRTC'
	pod 'SinchService'

	pod 'IQAudioRecorderController'
	pod 'JSQMessagesViewController'
	pod 'MBProgressHUD'
	pod 'ProgressHUD'
	pod 'Reachability'
	pod 'RNCryptor', '~> 3.0.1'
	pod 'RNGridMenu'
	pod 'SWTableViewCell'
end
